apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: greeter
  namespace: ars-dev
spec:
  template:
    spec:
      containers:
      - image: docker.io/rianmachado/demo-http-resteasy:v1
        livenessProbe:
          httpGet:
            path: /health/live
        readinessProbe:
          httpGet:
            path: /health/ready
